# Generated by Django 3.2.3 on 2021-05-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_name_short',
            field=models.CharField(default='Null', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
