# Generated by Django 3.2.4 on 2021-06-15 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_questionpaper_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('name_1', models.CharField(max_length=7)),
                ('name_2', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.exam'),
        ),
    ]
