# Generated by Django 3.2.3 on 2021-05-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_subject_subject_name_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_name_short',
        ),
    ]
