# Generated by Django 3.2.3 on 2021-05-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_subject_subject_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_name_short',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
