# Generated by Django 3.2.4 on 2021-06-13 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_subject_subject_name_short'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionpaper',
            name='unique paper',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='exam',
            field=models.CharField(choices=[('MST-1', 'MST-1'), ('MST-2', 'MST-2'), ('END-SEM', 'END-SEM')], default='MST-1', max_length=7),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='semester',
            field=models.CharField(choices=[('ODD', 'ODD (Feb-May)'), ('EVEN', 'EVEN (Aug-Dec)')], default='ODD', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='questionpaper',
            constraint=models.UniqueConstraint(fields=('branch', 'subject', 'year', 'semester', 'exam'), name='unique paper'),
        ),
    ]
