# Generated by Django 3.2.4 on 2021-06-13 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210613_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='id',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
