# Generated by Django 3.2.4 on 2021-06-13 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210613_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='uuid',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
